[project]
name = "numericalMethods"
version = "0.1.0"
description = "A library for numerical methods"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
